### ISSUE TITLE
Disabled headers get imported

### ISSUE THREAD

**Issue by exploide** [grafana/postman-to-k6#102]
When a request from the Postman collections contains a disabled HTTP header

```json
"header": [
    {
        "key": "Content-Type",
        "value": "application/xml",
        "type": "text",
        "disabled": true
    }
]
```

it ends up being enabled in the generated k6 script:

```json
headers: {
    "Content-Type": "application/xml"
}
```

This may break the request processing and leads to different results when run from Postman or k6.

I propose don't importing disabled headers or alternatively, have them commented out in the resulting script (if this is easily possible).

**Comment by thim81** [comment]
@exploide, I have provided a alternative forked NPM package version that contains this new feature:

Replace in your packages.json:
```
"dependencies": {
    "postman-to-k6": "^1.5.0"
  }
```
to
```
"dependencies": {
    "@apideck/postman-to-k6": "^1.6.0"
  }
```

This is a forked NPM package, to help overcome the issue. The current maintainers are quite overloaded by the acquisition of K6 by Grafana. By forking the repo & package, users can keep using new PR's & (security) fixes. At a later stage the changes can potentially be merged back in the original postman-to-k6 repo.

The [changelog](https://github.com/apideck-libraries/postman-to-k6/blob/main/CHANGELOG.md) contains the differences between the original package & the forked version.

**Comment by ppcano** [comment]
Apologies for the inactivity on this project. 

Due to the inability to properly support this project, the k6 team has decided not to continue its development. The primary reason is that k6 scope has grown significantly with the launch of k6 extensions. The team is prioritizing extending k6 capabilities over the converters.  

We suggest you post your issue at [api-deck/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). The project is active and maintained on this fork.
