### ISSUE TITLE
Double encoding of URL parameters

### ISSUE THREAD

**Issue by exploide** [grafana/postman-to-k6#104]
After converting a postman collection, I noticed that some of the `address` attributes in the generated k6 requests did contain double encoded values. This happened when the URL in the collection contains variables.

So instead of `{{variable}}` I got `%7B%7Bvariable%7D%7D`. And a `%20` was double encoded to `%2520`.

I needed to clean that up manually after the conversion. Think this is a bug.

**Comment by thim81** [comment]
@exploide Can you share an example postman collection where this double encoding is the result?

**Comment by exploide** [comment]
I think @MopsiMauser has an example in #106 which appears to be the same issue.

**Comment by thim81** [comment]
@exploide  

I have made a PR to solve this unwanted encoding, more info on the origin of issue can be found in the PR #113

**Comment by thim81** [comment]
For those experiencing the same issue, I have provided a alternative temporary NPM package version that contains this fix:

Replace in your packages.json:
```
"dependencies": {
    "postman-to-k6": "^1.5.0"
  }
```
to
```
"dependencies": {
    "@apideck/postman-to-k6": "^1.6.0"
  }
```

This is a forked NPM package, to help overcome the issue. The current maintainers are quite overloaded by the acquisition of K6 by Grafana. By forking the repo & package, users can keep using new PR's & (security) fixes. At a later stage the changes can potentially be merged back in the original postman-to-k6 repo.

The [changelog](https://github.com/apideck-libraries/postman-to-k6/blob/main/CHANGELOG.md) contains the differences between the original package & the forked version.

**Comment by ppcano** [comment]
Apologies for the inactivity on this project. 

Due to the inability to properly support this project, the k6 team has decided not to continue its development. The primary reason is that k6 scope has grown significantly with the launch of k6 extensions. The team is prioritizing extending k6 capabilities over the converters.  

We suggest you post your issue at [api-deck/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). The project is active and maintained on this fork.
