### ISSUE TITLE
Postman variables in query string don't get replaced

### ISSUE THREAD

**Issue by MopsiMauser** [grafana/postman-to-k6#106]
Hello,

Postman variables in the query string don't get replaced when the request is invoked. I think the problem is that the placeholders for the variables are getting URL encoded within the conversion. I attached a Postman collection and the created k6 script.

Command Line: postman-to-k6 TestCollection.postman_collection.json -o TestCollection.js

Best Regards

[TestCollection.js.txt](https://github.com/k6io/postman-to-k6/files/6593841/TestCollection.js.txt)
[TestCollection.postman_collection.json.txt](https://github.com/k6io/postman-to-k6/files/6593842/TestCollection.postman_collection.json.txt)

**Comment by thim81** [comment]
@MopsiMauser 

I have made a PR to solve this unwanted encoding, more info on the origin can be found in the PR #113

**Comment by rcrichton** [comment]
I have variables for both host and port in my postman collection. Could this be the reason those aren't getting replaced as well?

**Comment by thim81** [comment]
@rcrichton The issue was related to the query string part which got incorrectly encoded. 

For the definition of the host and port, you can use the available environment variable option https://github.com/grafana/postman-to-k6#environment-variables

By passing a postman environment config file, the variables will be inserted in the generated k6 script.

**Comment by thim81** [comment]
For those experiencing the same issue, I have provided a alternative temporary NPM package version that contains this fix:

Replace in your packages.json:
```
"dependencies": {
    "postman-to-k6": "^1.5.0"
  }
```
to
```
"dependencies": {
    "@apideck/postman-to-k6": "^1.6.0"
  }
```

This is a temporary NPM package, to help overcome the issue. The current maintainers are quite overloaded by the acquisition of K6 by Grafana. By forking the repo & package, users can keep using new PR's & (security) fixes. At a later stage the changes can potentially be merged back in the original postman-to-k6 repo.

The [changelog](https://github.com/apideck-libraries/postman-to-k6/blob/main/CHANGELOG.md) contains the differences between the original package & the forked version.

**Comment by MopsiMauser** [comment]
@thim81 thank you for your effort!! I just tested it and it works now <3

**Comment by ppcano** [comment]
Apologies for the inactivity on this project. 

Due to the inability to properly support this project, the k6 team has decided not to continue its development. The primary reason is that k6 scope has grown significantly with the launch of k6 extensions. The team is prioritizing extending k6 capabilities over the converters.  

We suggest you post your issue at [api-deck/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). The project is active and maintained on this fork.
