### ISSUE TITLE
When will you support postman.setNextRequest() ?

### ISSUE THREAD

**Issue by anagai** [grafana/postman-to-k6#109]
We use alot of postman.setNextRequest() in our postman tests to do polling to confirm a async process completed. Since this library does not support this we cannot use this library for existing postman tests. I would think this would be a good feature to support.

**Comment by simskij** [comment]
Thanks for letting us know! Would you be able to provide a minimal repro for this? I'm thinking that we might be able to use setNextRequest to sort the request order in the script output, and then discard it.

**Comment by ppcano** [comment]
Apologies for the inactivity on this project. 

Due to the inability to properly support this project, the k6 team has decided not to continue its development. The primary reason is that k6 scope has grown significantly with the launch of k6 extensions. The team is prioritizing extending k6 capabilities over the converters.  

We suggest you post your issue at [api-deck/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). The project is active and maintained on this fork.
