### ISSUE TITLE
Postman variables default to original value if undefined

### ISSUE THREAD

**Issue by mattcollins107** [grafana/postman-to-k6#53]
https://github.com/loadimpact/postman-to-k6/blob/9e3d5083682092c90b1d92fc22af6e96d2118600/lib/shim/core.js#L530

We have a system where the POST body can contain formatted data like `{{some_string}}`, and this works fine in Postman because when it thinks it finds a variable but that variable does not exist, it defaults to just sending the original string in the request.  But this line breaks the API call, because it uses the string `undefined` instead of defaulting back to the original.  

Replacing `undef` with `"{{" + name + "}}"` makes this work correctly.

**Comment by simskij** [comment]
This makes sense as the purpose of the tool is to generate a k6 script that behaves as the collection it originated from.

**Comment by ppcano** [comment]
Apologies for the inactivity on this project. 

Due to the inability to properly support this project, the k6 team has decided not to continue its development. The primary reason is that k6 scope has grown significantly with the launch of k6 extensions. The team is prioritizing extending k6 capabilities over the converters.  

We suggest you post your issue at [api-deck/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). The project is active and maintained on this fork.
