### ISSUE TITLE
Add default awsv4 service name

### ISSUE THREAD

**Issue by daoz1026** [grafana/postman-to-k6#56]
Hello

 First, bravo for this great tool : ) 
 I'am using this to convert all our Postman collection into k6 script, and I had a tons of http 403 response, found out that the generated k6 script does not have a default value for AWS service name, if this field is left empty in the Postman interface.

![image](https://user-images.githubusercontent.com/14372156/77769917-ca291b00-7044-11ea-9553-fa6ff4a5c1d4.png)

postman 
`AWS4-HMAC-SHA256 Credential=XXX/XXX/eu-central-1/execute-api/aws4_request ...`

post-to-k6
`AWS4-HMAC-SHA256 Credential=XXX/XXX/eu-central-1//aws4_request`

 A suggestion from me would be to set the default service name value to `execute-api`, and eventually for all other value that are auto generated by Postman if left blank.

Regards

**Comment by ppcano** [comment]
Apologies for the inactivity on this project. 

Due to the inability to properly support this project, the k6 team has decided not to continue its development. The primary reason is that k6 scope has grown significantly with the launch of k6 extensions. The team is prioritizing extending k6 capabilities over the converters.  

We suggest you post your issue at [api-deck/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). The project is active and maintained on this fork.
