### ISSUE TITLE
Type error when passing command line options

### ISSUE THREAD

**Issue by ronfeldman** [grafana/postman-to-k6#71]
### The problem ###
When an option is "blank" in Postman, it is exported in this format:

"src": [],

When postman-to-k6 encounters this value, it gives the following error on the command line:

`The "path" argument must be of type string. Received type object`

### Workaround ###
Editing the exported collection, changing the [] to "", before converting it works around the problem.

## This causes the error ##
`									"key": "sampleFile2",
									"type": "file",
									"src": [],
									"disabled": true
								},`

## This works around the error ##
`								{
									"key": "sampleFile2",
									"type": "file",
									"src": "",
									"disabled": true
								},`

**Comment by simskij** [comment]
Well spotted! It should likely check for empty arrays, and in that case, just skip them as well.
Thanks for bringing this to my attention!

**Comment by ppcano** [comment]
Apologies for the inactivity on this project. 

Due to the inability to properly support this project, the k6 team has decided not to continue its development. The primary reason is that k6 scope has grown significantly with the launch of k6 extensions. The team is prioritizing extending k6 capabilities over the converters.  

We suggest you post your issue at [api-deck/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). The project is active and maintained on this fork.
