### ISSUE TITLE
Dynamic Variables

### ISSUE THREAD

**Issue by dbacelar4i** [grafana/postman-to-k6#90]
Hi,

I have a problem with dynamic variables like: 

{{$randomFirtsName}}, {{$randomLatitude}}, {{$randomLongitude}}, {{$randomColor}}, {{$randomCity}}, {{$randomCountry}}, {{$randomAdjective}}, {{$randomFileName}}

After conversion, they are not recognized and cause an error when performing the load test.

**Comment by thim81** [comment]
Hi @dbacelar4i 

I have created a PR to provide full support of all Postman dynamic variables.
https://github.com/k6io/postman-to-k6/pull/92

So keep an eye out of the progress of the PR.

**Comment by thim81** [comment]
For those experiencing the same issue, I have provided a forked NPM package version that contains this fix:

Replace in your packages.json:
```
"dependencies": {
    "postman-to-k6": "^1.5.0"
  }
```
to
```
"dependencies": {
    "@apideck/postman-to-k6": "^1.6.0"
  }
```

This is a forked NPM package, to provide this new feature. The current maintainers are quite overloaded by the acquisition of K6 by Grafana. By forking the repo & package, users can keep using new PR's & (security) fixes. At a later stage the changes can potentially be merged back in the original postman-to-k6 repo.

The [changelog](https://github.com/apideck-libraries/postman-to-k6/blob/main/CHANGELOG.md) contains the differences between the original package & the forked version.

**Comment by ppcano** [comment]
Apologies for the inactivity on this project. 

Due to the inability to properly support this project, the k6 team has decided not to continue its development. The primary reason is that k6 scope has grown significantly with the launch of k6 extensions. The team is prioritizing extending k6 capabilities over the converters.  

We suggest you post your issue at [api-deck/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). The project is active and maintained on this fork.
