### ISSUE TITLE
Unrecognized body mode: file

### ISSUE THREAD

**Issue by stlr00** [grafana/postman-to-k6#98]
![image](https://user-images.githubusercontent.com/61075639/117851205-c1b69280-b28e-11eb-862f-d61241094ae2.png)

![image](https://user-images.githubusercontent.com/61075639/117851056-9cc21f80-b28e-11eb-8370-b7e2161311c0.png)

**Comment by simskij** [comment]
Hey!

Yeah, [these](https://github.com/k6io/postman-to-k6/blob/c4e364915878a7330e0dffa9e749eb657f13213a/lib/generate/Request/analyze.js#L78-L88) are the supported body modes of the tool currently. I'll go ahead and label this as a feature request. 

If anyone would like to have a stab at it, I'd be more than happy to assist with PR reviews and such, but I unfortunately don't have enough room in my pipeline to do it myself any time soon. 

Best,
Simme

**Comment by ppcano** [comment]
Apologies for the inactivity on this project. 

Due to the inability to properly support this project, the k6 team has decided not to continue its development. The primary reason is that k6 scope has grown significantly with the launch of k6 extensions. The team is prioritizing extending k6 capabilities over the converters.  

We suggest you post your issue at [api-deck/postman-to-k6](https://github.com/apideck-libraries/postman-to-k6). The project is active and maintained on this fork.
